version: "3"

networks:
  greenpeace:

services:
  db-mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
    volumes:
      - ./docker/db-mysql/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./docker/db-mysql/mysql-volume:/var/lib/mysql
    ports:
      - ${DB_MYSQL_PUBLISH_PORT}:${DB_MYSQL_PORT}
    networks:
      - greenpeace

  db-phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db-mysql
    environment:
      - PMA_HOST=db-mysql
      - PMA_PORT=${DB_MYSQL_PORT}
      - PMA_USER=${DB_MYSQL_USER}
      - PMA_PASSWORD=${DB_MYSQL_PASSWORD}
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB_PHPMYADMIN_PUBLISH_PORT}:80
    networks:
      - greenpeace

  api:
    image: node:18
    restart: unless-stopped
    depends_on:
      - db-mysql
    environment:
      - API_PUBLISH_HOST=${API_PUBLISH_HOST}
      - API_PUBLISH_PROTOCOL=${API_PUBLISH_PROTOCOL}
      - API_PUBLISH_PORT=${API_PUBLISH_PORT}
      - API_PORT=${API_PORT}
      - API_PREFIX_PATH=${API_PREFIX_PATH}
      - API_MYSQL_USER=${DB_MYSQL_USER}
      - API_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - API_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - API_MYSQL_HOST=${DB_MYSQL_HOST}
      - API_MYSQL_PUBLISH_PORT=${DB_MYSQL_PUBLISH_PORT}
      - API_MYSQL_PORT=${DB_MYSQL_PORT}
      - TZ=America/Argentina/Buenos_Aires
      - API_EMAIL_HOST=${API_EMAIL_HOST}
      - API_EMAIL_PORT=${API_EMAIL_PORT}
      - API_EMAIL_AUTH_USER=${API_EMAIL_AUTH_USER}
      - API_EMAIL_AUTH_PASS=${API_EMAIL_AUTH_PASS}
      - API_EMAIL_FROM=${API_EMAIL_FROM}
      - API_EMAIL_ERROR_RECIPIENT=${API_EMAIL_ERROR_RECIPIENT}
      - API_URL_GET_PAGOS=${API_URL_GET_PAGOS}
      - API_URL_CREATE_STAGING=${API_URL_CREATE_STAGING}
      - API_URL_AUTH_SF=${API_URL_AUTH_SF}
      - API_AUTH_SF_GRANT_TYPE=${API_AUTH_SF_GRANT_TYPE}
      - API_AUTH_SF_CLIENT_ID=${API_AUTH_SF_CLIENT_ID}
      - API_AUTH_SF_CLIENT_SECRET=${API_AUTH_SF_CLIENT_SECRET}
      - API_AUTH_SF_USERNAME=${API_AUTH_SF_USERNAME}
      - API_AUTH_SF_PASSWORD=${API_AUTH_SF_PASSWORD}
      - API_SF_S360AIE__CAMPAIGNID__C=${API_SF_S360AIE__CAMPAIGNID__C}
      - API_SF_RECORDTYPEID=${API_SF_RECORDTYPEID}      
      - API_TBK_COMMERCE_CODE_MALL=${API_TBK_COMMERCE_CODE_MALL}
      - API_TBK_API_KEY=${API_TBK_API_KEY}
      - API_TBK_ENVIRONMENT=${API_TBK_ENVIRONMENT}
      - API_TBK_COMMERCE_CODE_STORE=${API_TBK_COMMERCE_CODE_STORE}
      - API_NODECRON_SCHEDULED_APP_TIME=${API_NODECRON_SCHEDULED_APP_TIME}
      - API_URL_NEW_TRANSACTION_ENDPOINT=${API_URL_NEW_TRANSACTION_ENDPOINT}
      - API_URL_PATCH_TRANSACTION_ENDPOINT=${API_URL_PATCH_TRANSACTION_ENDPOINT}
      - API_CLOSE_DATE=${API_CLOSE_DATE}
    volumes:
      - ./api:/home/app
    working_dir: /home/app
    command: bash -c "yarn install && yarn start:dev"
    ports:
      - ${API_PUBLISH_PORT}:${API_PORT}
    networks:
      - greenpeace

  web:
    image: node:18
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - PORT=${WEB_PUBLISH_PORT}
      - REACT_APP_API_URL=${WEB_API_URL}
      - TZ=America/Argentina/Buenos_Aires
      - REACT_APP_WEB_HOME_UTM=${WEB_HOME_UTM}
    volumes:
      - ./web:/home/app
    working_dir: /home/app
    command: bash -c "yarn install && yarn start"
    ports:
      - ${WEB_PUBLISH_PORT}:${WEB_PUBLISH_PORT}
    networks:
      - greenpeace
