enum TransaccionStates {
  CREADA = "CREADA",
  INICIALIZADA = "INICIALIZADA",
  ERROR = "ERROR",
  CONFIRMACION_PENDIENTE = "CONFIRMACION_PENDIENTE",
  CONFIRMADA_TBK = "CONFIRMADA_TBK",
  CONFIRMADA_SF = "CONFIRMADA_SF",
  FINALIZADA_SF = "FINALIZADA SF OK",
  FINALIZADA_SF_ERROR = "FINALIZADA SF ERROR",
}

export default TransaccionStates;
